# Generated by Django 3.1 on 2020-10-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='所属app')),
            ],
            options={
                'verbose_name': 'app名字',
                'verbose_name_plural': 'app名字',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='所属app')),
                ('dict_key', models.CharField(max_length=32, verbose_name='字典key')),
                ('dict_value', models.CharField(max_length=256, verbose_name='字典值')),
            ],
            options={
                'verbose_name': '测试配置',
                'verbose_name_plural': '测试配置',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=20, verbose_name='模块名称')),
                ('title', models.CharField(max_length=30, verbose_name='用例名称')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('url', models.CharField(max_length=128, verbose_name='接口名称')),
                ('run', models.CharField(max_length=4, verbose_name='是否运行')),
                ('headers', models.CharField(max_length=128, verbose_name='headers请求头')),
                ('pre_case_id', models.IntegerField(default=-1, verbose_name='是否有前置用例id')),
                ('pre_fields', models.CharField(max_length=128, verbose_name='前置的字段')),
                ('request_data', models.CharField(max_length=128, verbose_name='请求参数')),
                ('expect_result', models.CharField(max_length=4, verbose_name='预期结果')),
                ('assert_type', models.CharField(max_length=32, verbose_name='断言类型')),
                ('pass_or_not', models.CharField(max_length=10, verbose_name='是否通过')),
                ('msg', models.CharField(max_length=128, verbose_name='测试用例额外描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('response', models.TextField(max_length=128, verbose_name='实际结果')),
                ('app_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCaseApp.AppName', verbose_name='业务应用')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
            },
        ),
    ]
