# Generated by Django 3.1.3 on 2020-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCaseApp', '0002_auto_20201022_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='msg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pass_or_not',
            field=models.CharField(blank=True, default='unknown', max_length=10, null=True, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pre_fields',
            field=models.CharField(max_length=256, verbose_name='需要前置字段'),
        ),
        migrations.AlterField(
            model_name='case',
            name='response',
            field=models.TextField(blank=True, default='', null=True, verbose_name='实际结果'),
        ),
        migrations.AlterField(
            model_name='case',
            name='url',
            field=models.CharField(max_length=256, verbose_name='接口(url)'),
        ),
    ]
